### PR TITLE
Fix for improper constructor call

### PR DESCRIPTION
**Pull request by MinusWall**

### CODE REVIEW

**Comment by AlexIII** [comment]
Mistake at
https://github.com/NeiroNx/RTCLib/blob/bf118ec9b57d4939e3d8c1b0af8a57830973ecf0/src/RTClib.cpp#L121-L122
should be
```
SetDate(_date);
SetTime(_time);
```

**Comment by AlexIII** [comment]
Besides, it's better to reuse the first array twice and save 8 bytes of stack...

**Comment by MinusWall** [comment]
Thanks, fixed. 
Please let me know if I need to do anything more to merge to main branch, as I am lost.

**Comment by 45gfg9** [comment]
Oh shoot, this bug...
Thanks a lot for fixing it!
(Maybe someday we need to refactor this whole thing...)

**Comment by MinusWall** [comment]
No problem. It was weird - garbage in clock date, no compiler warnings. 
I thought I am running out of memory >.<

**Pull request merged**
